util.PrecacheModel( "models/hybridphysx/precrash_airliner.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_primary_debris_1.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_primary_debris_2.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_primary_debris_3.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_primary_debris_4.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_fuselage_secondary_1.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_fuselage_secondary_2.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_fuselage_secondary_3.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_fuselage_secondary_4.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_left_wing_secondary.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_right_wing_secondary_1.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_right_wing_secondary_2.mdl" )
util.PrecacheModel( "models/hybridphysx/airliner_tail_secondary.mdl" )
CreateConVar( "l4dplanecrash_gonetime", 99999999, FCVAR_REPLICATED, "How many seconds will pass before the plane automatically removes itself", 15, nil )
CreateConVar( "l4dplanecrash_sound", "animation/airport_rough_crash_seq.wav", FCVAR_REPLICATED, "The sound the crash will play", nil, nil )