//if you know anything about coding then get away from here, spare your eyes for you know not of what horrors lay below this message

AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")

include("shared.lua")

util.AddNetworkString( "PlaneCrashEffects" )
util.AddNetworkString( "PlaneCrashDebug" )

function ENT:Initialize()
   local gonetimer = cvars.Number( "l4dplanecrash_gonetime", -1 )
   local planesound = cvars.String( "l4dplanecrash_sound", "animation/airport_rough_crash_seq.wav" )
   local startmap = game.GetMap()
   self:SetModel("models/hybridphysx/precrash_airliner.mdl")
   if startmap == "c11m5_runway" then
      self:SetPos( Vector( -5136, 10060, -192 ) )
      self:SetAngles( Angle( 0, 180, 0 ) )
   end
   if startmap == "c11m5_runway_ep2" then
      self:SetPos( Vector( -3181, 3404, -192 ) )
      self:SetAngles( Angle( 0, 180, 0 ) )
   end
   timer.Simple( 0.01, function() self:SetSequence( "approach" ) end )
   self:ResetSequence( "approach" )
   self:EmitSound( planesound, 0, 100, 1, CHAN_AUTO )
   local spawnangles = self:GetAngles()
   self:SetAngles( spawnangles - Angle( 0, 180, 0 ) )
   local spawnangles = self:GetAngles()
   local spawnpos = self:GetPos()

   -- SERVER DEBUG: log spawnpos so we know the entity origin
   print( "[PLANECRASH] ENT spawned. spawnpos = " .. tostring( spawnpos ) )
   print( "[PLANECRASH] spawnangles = " .. tostring( spawnangles ) )
   print( "[PLANECRASH] map = " .. startmap )

   local fuseA = ents.Create( "prop_dynamic_override" )
   local fuseB = ents.Create( "prop_dynamic_override" )
   local fuseC = ents.Create( "prop_dynamic_override" )
   local fuseD = ents.Create( "prop_dynamic_override" )
   local fuseE = ents.Create( "prop_dynamic_override" )
   local fuseF = ents.Create( "prop_dynamic_override" )
   local fuseG = ents.Create( "prop_dynamic_override" )
   local fuseH = ents.Create( "prop_dynamic_override" )
   local fuseI = ents.Create( "prop_dynamic_override" )
   local fuseJ = ents.Create( "prop_dynamic_override" )
   local fuseK = ents.Create( "prop_dynamic_override" )
   local fuseL = ents.Create( "prop_dynamic_override" )
   timer.Simple( 14.95, function() fuseA:SetModel("models/hybridphysx/airliner_primary_debris_1.mdl") end )
   timer.Simple( 14.95, function() fuseA:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseA:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseA:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseA:Spawn() end )
   timer.Simple( 14.96, function() fuseA:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseB:SetModel("models/hybridphysx/airliner_primary_debris_2.mdl") end )
   timer.Simple( 14.95, function() fuseB:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseB:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseB:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseB:Spawn() end )
   timer.Simple( 14.96, function() fuseB:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseC:SetModel("models/hybridphysx/airliner_primary_debris_3.mdl") end )
   timer.Simple( 14.95, function() fuseC:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseC:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseC:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseC:Spawn() end )
   timer.Simple( 14.96, function() fuseC:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseD:SetModel("models/hybridphysx/airliner_primary_debris_4.mdl") end )
   timer.Simple( 14.95, function() fuseD:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseD:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseD:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseD:Spawn() end )
   timer.Simple( 14.96, function() fuseD:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseE:SetModel("models/hybridphysx/airliner_fuselage_secondary_1.mdl") end )
   timer.Simple( 14.95, function() fuseE:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseE:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseE:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseE:Spawn() end )
   timer.Simple( 14.96, function() fuseE:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseF:SetModel("models/hybridphysx/airliner_fuselage_secondary_2.mdl") end )
   timer.Simple( 14.95, function() fuseF:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseF:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseF:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseF:Spawn() end )
   timer.Simple( 14.96, function() fuseF:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseG:SetModel("models/hybridphysx/airliner_fuselage_secondary_3.mdl") end )
   timer.Simple( 14.95, function() fuseG:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseG:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseG:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseG:Spawn() end )
   timer.Simple( 14.96, function() fuseG:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseH:SetModel("models/hybridphysx/airliner_fuselage_secondary_4.mdl") end )
   timer.Simple( 14.95, function() fuseH:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseH:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseH:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseH:Spawn() end )
   timer.Simple( 14.96, function() fuseH:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseI:SetModel("models/hybridphysx/airliner_left_wing_secondary.mdl") end )
   timer.Simple( 14.95, function() fuseI:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseI:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseI:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseI:Spawn() end )
   timer.Simple( 14.96, function() fuseI:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseJ:SetModel("models/hybridphysx/airliner_right_wing_secondary_1.mdl") end )
   timer.Simple( 14.95, function() fuseJ:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseJ:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseJ:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseJ:Spawn() end )
   timer.Simple( 14.96, function() fuseJ:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseK:SetModel("models/hybridphysx/airliner_right_wing_secondary_2.mdl") end )
   timer.Simple( 14.95, function() fuseK:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseK:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseK:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseK:Spawn() end )
   timer.Simple( 14.96, function() fuseK:ResetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseL:SetModel("models/hybridphysx/airliner_tail_secondary.mdl") end )
   timer.Simple( 14.95, function() fuseL:SetPos( spawnpos ) end )
   timer.Simple( 14.95, function() fuseL:SetAngles( spawnangles ) end )
   timer.Simple( 14.96, function() fuseL:SetSequence( "boom" ) end )
   timer.Simple( 14.95, function() fuseL:Spawn() end )
   timer.Simple( 14.96, function() fuseL:ResetSequence( "boom" ) end )

   -- Broadcast spawnpos the moment debris spawns. This is reliable.
   -- The client will delay effects internally and log positions for calibration.
   timer.Simple( 14.95, function()
      print( "[PLANECRASH] Broadcasting PlaneCrashEffects. spawnpos = " .. tostring( spawnpos ) )
      net.Start( "PlaneCrashEffects" )
         net.WriteVector( spawnpos )
         net.WriteVector( spawnangles:Forward() )  -- forward dir for offset math
      net.Broadcast()
   end )

   -- Debug broadcast at t=17, t=20, t=23 so client can log fuseA positions
   -- over time to find the true visual resting place
   timer.Simple( 17.0, function()
      if not IsValid( fuseA ) then
         print( "[PLANECRASH DEBUG t=17] fuseA is INVALID" )
         return
      end
      local p = fuseA:GetPos()
      print( "[PLANECRASH DEBUG t=17] fuseA:GetPos() = " .. tostring(p) )
      net.Start( "PlaneCrashDebug" )
         net.WriteFloat( 17 )
         net.WriteVector( p )
      net.Broadcast()
   end )

   timer.Simple( 20.0, function()
      if not IsValid( fuseA ) then
         print( "[PLANECRASH DEBUG t=20] fuseA is INVALID" )
         return
      end
      local p = fuseA:GetPos()
      print( "[PLANECRASH DEBUG t=20] fuseA:GetPos() = " .. tostring(p) )
      net.Start( "PlaneCrashDebug" )
         net.WriteFloat( 20 )
         net.WriteVector( p )
      net.Broadcast()
   end )

   timer.Simple( 23.0, function()
      if not IsValid( fuseA ) then
         print( "[PLANECRASH DEBUG t=23] fuseA is INVALID" )
         return
      end
      local p = fuseA:GetPos()
      print( "[PLANECRASH DEBUG t=23] fuseA:GetPos() = " .. tostring(p) )
      net.Start( "PlaneCrashDebug" )
         net.WriteFloat( 23 )
         net.WriteVector( p )
      net.Broadcast()
   end )

   timer.Simple( 20.5, function() util.ScreenShake( spawnpos, 4, 100, 4, 16000 ) end )
   timer.Simple( 23.0, function() util.ScreenShake( spawnpos, 4, 100, 4, 16000 ) end )
   timer.Simple( 24.0, function() util.ScreenShake( spawnpos, 4, 100, 4, 16000 ) end )
   timer.Simple( 26.0, function() util.ScreenShake( spawnpos, 4, 100, 4, 16000 ) end )
   timer.Simple( 14.96, function() self:Remove() end )
   timer.Simple( gonetimer, function() fuseA:Remove() end )
   timer.Simple( gonetimer, function() fuseB:Remove() end )
   timer.Simple( gonetimer, function() fuseC:Remove() end )
   timer.Simple( gonetimer, function() fuseD:Remove() end )
   timer.Simple( gonetimer, function() fuseE:Remove() end )
   timer.Simple( gonetimer, function() fuseF:Remove() end )
   timer.Simple( gonetimer, function() fuseG:Remove() end )
   timer.Simple( gonetimer, function() fuseH:Remove() end )
   timer.Simple( gonetimer, function() fuseI:Remove() end )
   timer.Simple( gonetimer, function() fuseJ:Remove() end )
   timer.Simple( gonetimer, function() fuseK:Remove() end )
   timer.Simple( gonetimer, function() fuseL:Remove() end )
end

function ENT:Think()

	self:NextThink( CurTime() )
	return true
end
